repos:
- repo: https://github.com/pycqa/isort
  rev: 6.0.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    args: ["--line-length", "88"]